### ISSUE TITLE
TypeError: options.warning is not a function

### ISSUE THREAD

**Issue by bitGatito** [wooorm/bcp-47#22]
Using the package as: `const schema = parse('x-whatevertag', {warning: true})`, results in error:

```file:///C:/Users/.../node_modules/bcp-47/lib/parse.js:288
     if (options.warning) options.warning(reason, code, offset)
                                 ^
TypeError: options.warning is not a function
     at fail (file:///C:/Users/.../node_modules/bcp-47/lib/parse.js:288:34)
     at parse (file:///C:/Users/.../node_modules/bcp-47/lib/parse.js:258:18)
    at file:///C:/Users/.../src/test.js:3:16```

**Comment by wooorm** [comment]
Hi! You use TypeScript. TypeScript tells you that you pass wrong input. That’s why TypeScript exists. Please use the types provided or read the docs: https://github.com/wooorm/bcp-47#optionswarning
